---
# Production Environment Inventory
# Critical production systems with high availability

all:
  children:
    windows:
      children:
        domain_controllers:
          hosts:
            prod-dc01.company.com:
              ansible_host: 10.0.1.10
              windows_domain_role: primary_dc
              os_version: "2022"
              site: primary
            prod-dc02.company.com:
              ansible_host: 10.0.1.11
              windows_domain_role: secondary_dc
              os_version: "2022"
              site: primary
            prod-dc03.company.com:
              ansible_host: 10.0.1.20
              windows_domain_role: secondary_dc
              os_version: "2022"
              site: dr
              
        web_servers:
          hosts:
            prod-web01.company.com:
              ansible_host: 10.0.2.10
              iis_version: "10"
              ssl_certificates:
                - www.company.com
                - api.company.com
              cluster_node: 1
            prod-web02.company.com:
              ansible_host: 10.0.2.11
              iis_version: "10"
              load_balanced: true
              cluster_node: 2
            prod-web03.company.com:
              ansible_host: 10.0.2.12
              iis_version: "10"
              load_balanced: true
              cluster_node: 3
              
        database_servers:
          hosts:
            prod-sql01.company.com:
              ansible_host: 10.0.3.10
              sql_version: "2022"
              sql_instance: MSSQLSERVER
              sql_role: primary
              always_on_ag: ProductionAG
            prod-sql02.company.com:
              ansible_host: 10.0.3.11
              sql_version: "2022"
              sql_instance: MSSQLSERVER
              sql_role: secondary
              always_on_ag: ProductionAG
            prod-sql03.company.com:
              ansible_host: 10.0.3.20
              sql_version: "2022"
              sql_instance: MSSQLSERVER
              sql_role: dr_secondary
              always_on_ag: ProductionAG
              site: dr
                
        application_servers:
          hosts:
            prod-app[01:06].company.com:
              ansible_host_pattern: "10.0.4.[10:15]"
              dotnet_version: "8.0"
              cluster_member: true
              performance_monitoring: true
              
        file_servers:
          hosts:
            prod-fs01.company.com:
              ansible_host: 10.0.5.10
              dfs_root: true
              backup_schedule: hourly
            prod-fs02.company.com:
              ansible_host: 10.0.5.11
              dfs_member: true
              backup_schedule: hourly
              
        citrix_servers:
          hosts:
            prod-ctx[01:04].company.com:
              ansible_host_pattern: "10.0.6.[10:13]"
              citrix_version: "7.15"
              published_apps:
                - Microsoft Office
                - ERP System
                - Custom Apps

  vars:
    # Global Windows connection settings
    ansible_user: "{{ vault_prod_admin_user }}"
    ansible_password: "{{ vault_prod_admin_password }}"
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: validate
    ansible_winrm_port: 5986
    ansible_winrm_scheme: https
    ansible_winrm_credssp_disable_tlsv1_2: false
    
    # Environment-specific variables
    environment_name: production
    domain_name: company.com
    dns_servers:
      - 10.0.1.10
      - 10.0.1.11
      - 8.8.8.8
    ntp_servers:
      - pool.ntp.org
      - time.nist.gov
    
    # Security settings for production environment
    security_level: maximum
    allow_rdp: false
    firewall_enabled: true
    windows_update_schedule: maintenance_window
    antivirus_enabled: true
    edr_enabled: true
    encryption_required: true
    
    # Backup and monitoring
    backup_enabled: true
    backup_schedule: continuous
    monitoring_enabled: true
    log_retention_days: 90
    compliance_scanning: true
    vulnerability_scanning: true
    
    # High availability settings
    ha_enabled: true
    disaster_recovery: true
    rpo_minutes: 15
    rto_minutes: 60