---
# Development Environment Inventory
# Windows servers for development and testing

all:
  children:
    windows:
      children:
        domain_controllers:
          hosts:
            dev-dc01.dev.local:
              ansible_host: 10.1.1.10
              windows_domain_role: primary_dc
              os_version: "2022"
            dev-dc02.dev.local:
              ansible_host: 10.1.1.11
              windows_domain_role: secondary_dc
              os_version: "2022"
              
        web_servers:
          hosts:
            dev-web01.dev.local:
              ansible_host: 10.1.2.10
              iis_version: "10"
              app_pools:
                - DefaultAppPool
                - DevAppPool
            dev-web02.dev.local:
              ansible_host: 10.1.2.11
              iis_version: "10"
              load_balanced: true
              
        database_servers:
          hosts:
            dev-sql01.dev.local:
              ansible_host: 10.1.3.10
              sql_version: "2022"
              sql_instance: MSSQLSERVER
              databases:
                - DevAppDB
                - TestDB
                
        application_servers:
          hosts:
            dev-app01.dev.local:
              ansible_host: 10.1.4.10
              dotnet_version: "8.0"
              applications:
                - MyDevApp
                - TestService
            dev-app02.dev.local:
              ansible_host: 10.1.4.11
              dotnet_version: "8.0"
              high_availability: true
              
        file_servers:
          hosts:
            dev-fs01.dev.local:
              ansible_host: 10.1.5.10
              shared_folders:
                - name: DevShared
                  path: "C:\\Shares\\DevShared"
                - name: UserProfiles
                  path: "C:\\Shares\\Profiles"
                  
        workstations:
          hosts:
            dev-ws[01:05].dev.local:
              ansible_host_pattern: "10.1.6.[10:14]"
              os_version: "11"
              managed_by_group_policy: true

  vars:
    # Global Windows connection settings
    ansible_user: "{{ vault_dev_admin_user }}"
    ansible_password: "{{ vault_dev_admin_password }}"
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_port: 5985
    ansible_winrm_scheme: http
    
    # Environment-specific variables
    environment_name: development
    domain_name: dev.local
    dns_servers:
      - 10.1.1.10
      - 10.1.1.11
    ntp_servers:
      - pool.ntp.org
      - time.windows.com
    
    # Security settings for dev environment
    security_level: medium
    allow_rdp: true
    firewall_enabled: true
    windows_update_schedule: manual
    
    # Backup and monitoring
    backup_enabled: false
    monitoring_enabled: true
    log_retention_days: 7