---
# Staging Environment Inventory
# Production-like environment for final testing

all:
  children:
    windows:
      children:
        domain_controllers:
          hosts:
            stage-dc01.stage.local:
              ansible_host: 10.2.1.10
              windows_domain_role: primary_dc
              os_version: "2022"
            stage-dc02.stage.local:
              ansible_host: 10.2.1.11
              windows_domain_role: secondary_dc
              os_version: "2022"
              
        web_servers:
          hosts:
            stage-web01.stage.local:
              ansible_host: 10.2.2.10
              iis_version: "10"
              ssl_certificates:
                - staging.company.com
            stage-web02.stage.local:
              ansible_host: 10.2.2.11
              iis_version: "10"
              load_balanced: true
              
        database_servers:
          hosts:
            stage-sql01.stage.local:
              ansible_host: 10.2.3.10
              sql_version: "2022"
              sql_instance: MSSQLSERVER
              backup_schedule: daily
              always_on_enabled: true
            stage-sql02.stage.local:
              ansible_host: 10.2.3.11
              sql_version: "2022"
              sql_instance: MSSQLSERVER
              sql_role: secondary
                
        application_servers:
          hosts:
            stage-app01.stage.local:
              ansible_host: 10.2.4.10
              dotnet_version: "8.0"
              performance_monitoring: true
            stage-app02.stage.local:
              ansible_host: 10.2.4.11
              dotnet_version: "8.0"
              cluster_member: true
              
        file_servers:
          hosts:
            stage-fs01.stage.local:
              ansible_host: 10.2.5.10
              dfs_enabled: true
              backup_schedule: daily

  vars:
    # Global Windows connection settings
    ansible_user: "{{ vault_stage_admin_user }}"
    ansible_password: "{{ vault_stage_admin_password }}"
    ansible_connection: winrm
    ansible_winrm_transport: kerberos
    ansible_winrm_server_cert_validation: validate
    ansible_winrm_port: 5986
    ansible_winrm_scheme: https
    
    # Environment-specific variables
    environment_name: staging
    domain_name: stage.local
    dns_servers:
      - 10.2.1.10
      - 10.2.1.11
    ntp_servers:
      - pool.ntp.org
      - time.windows.com
    
    # Security settings for staging environment
    security_level: high
    allow_rdp: false
    firewall_enabled: true
    windows_update_schedule: automatic
    antivirus_enabled: true
    
    # Backup and monitoring
    backup_enabled: true
    monitoring_enabled: true
    log_retention_days: 30
    compliance_scanning: true